services:
  - type: web
    name: projects-app-frontend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        sync: false 