services:
  - type: web
    name: projects-app-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        sync: false 